{% set name = "pydap" %}
{% set version = "3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydap-{{ version }}.tar.gz
  sha256: 0ee6cb7a4892ef22a15c4e2aa58b2656104c542c74faf16c580c56fdf97647ab

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.9
    - numpy
    - webob
    - jinja2
    - docopt-ng
    - beautifulsoup4
    - lxml
    - requests
    - importlib-metadata
    - importlib-resources

test:
  imports:
    - pydap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pydap.github.io/pydap/intro.html
  summary: A pure python implementation of the Data Access Protocol.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - Mikejmnez
