{% set version = "3.2.2" %}

package:
  name: pydap
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/Pydap/Pydap-{{ version }}.tar.gz
  sha256: 86326642e24f421595a74b0f9986da76d7932b277768f501fe214d72592bdc40

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - singledispatch
    - webob
    - jinja2
    - docopt
    - six >=1.4.0
    - mechanicalsoup
    # Optional.
    - gsw
    - scipy
    - requests
    #- coards
    # Server only.
    - gunicorn  # [not win]

test:
  imports:
    - pydap

about:
  home: http://pydap.org/
  license: MIT
  license_file: docs/license.rst
  summary: 'Pure Python Opendap/DODS client and server.'

extra:
  recipe-maintainers:
    - ocefpaf
