{% set version = "3.2.2" %}

package:
  name: pydap
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/Pydap/Pydap-{{ version }}.tar.gz
  sha256: 86326642e24f421595a74b0f9986da76d7932b277768f501fe214d72592bdc40
  patches:
    - gzip_PR126.patch

build:
  number: 1001
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"
  entry_points:
    - pydap = pydap.wsgi.app:main
    - dods = pydap.handlers.dap:dump

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - webob
    - jinja2
    - docopt
    - six >=1.4.0
    - mechanicalsoup
    - singledispatch  # [py27]

test:
  imports:
    - pydap
  requires:
    - gunicorn  # [not win]
    - pastedeploy  # [not win]
  commands:
    - pydap -h  # [not win]

about:
  home: http://pydap.org/
  license: MIT
  license_file: docs/license.rst
  summary: 'Pure Python Opendap/DODS client and server'

extra:
  recipe-maintainers:
    - ocefpaf
