{% set name = "pydap" %}
{% set version = "3.5.4" %}
{% set python_min = "3.10" %}

# handle undefined PYTHON in `noarch: python` outputs
{% if PYTHON is not defined %}{% set PYTHON = "$PYTHON" %}{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydap-{{ version }}.tar.gz
  sha256: 1ff6f783b6305a02ccd6e80fd4570b3db2be85435f00ddc827e821f32694df99

build:
  noarch: python
  number: 0

outputs:
  - name: "pydap"
    build:
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
        - setuptools >=64
        - setuptools-scm >=8
        - pip
      run:
        - python >={{ python_min }}
        - numpy >=2.0
        - requests
        - scipy
        # optional, server, but required to pass the import test
        - docopt-ng
        - jinja2
        - webob
    test:
      imports:
        - pydap
      requires:
        - python ={{ python_min }}
        - gunicorn  # [not win]
        - pastedeploy  # [not win]
        - pip
      commands:
        - pip check
        - pydap -h  # [not win]
  - name: "pydap-server"
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
        - setuptools >=64
        - setuptools-scm >=8
        - pip
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage("pydap", exact=True) }}
        - beautifulsoup4
        - docopt-ng
        - gunicorn
        - jinja2
        - lxml
        - PasteDeploy
        - Webob
    test:
      imports:
        - pydap
      requires:
        - python ={{ python_min }}
        - gunicorn  # [not win]
        - pastedeploy  # [not win]
        - pip
      commands:
        - pip check
        - pydap -h  # [not win]
about:
  home: https://pydap.github.io/pydap/intro.html
  summary: A pure python implementation of the Data Access Protocol.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - Mikejmnez
