travis:
  secure:
    BINSTAR_TOKEN: QH3Ce6VYnRwZT/tEgXcg59EUdWx5bM+LkyTyFy7pHH2MZcCideIZCibvnYSk22hfSkZm5QCBDdS/Jg8Dbnl8uqYNtC9j8H+QD/tW5lAhi2c5Iul+I0zb1sh0USslfxU25cu+zRqTs9uoK72R7vCaBWxnXfBY85PsagHfsYrW5eAsnnMQC6fKePwyQYe/pgG1tZho2OpgOWjvWeoBzUX67UgBLKw8f8yon0ImBZOIvadGe9wLICT5znjfFvfoGnfvAOLo45z31Y4nBMQseUYMGpGB4QeIRvVADjpeetWDGBBUqE8fMi3TeV058ukS1f8iBt+V4G7azBj00/v5lHwOU+g6TcLkvMQHGCUhiLjJzF66SXmoDL4YACVbjGxazw3fFRCG1Pszzu36wW8XaUSQKUDW6np/gSimqOvLcTi9WHahuio0zqs28b6LMN9DHoc1kDfkjVpei6bRzuPPtzqDux20oOMkp/byicFZR6XdSBKMBM2wka2z+g0CERrYsW7plTawlO0Mc78PPM2/12O95FFEvYbIfcabnkPS4xTEFj3KDe2Ub0zdGp8c5M4N45hTsovLSEy4uKQGic4vlRLdnsD34TD87gEt7b0Mj3bp6U9rIL7moRwcqavM5osk12HM4F3ZJUMw53y1hWDr0aVaO2Kqr+tCQ3WX1A8ZVveQTSs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
